#
#Auteur : François Hallereau
#Date : 10 février 2015
#Licence 3 informatique
#Université de Nantes
#

#Exercice 1 : Le Chapelier

chapelier: glpsol -m chapelier.mod -d chapelier.dat

#Exercice 2 : Les infirmières

nursesv1: glpsol -m nursesv1.mod -d nurses.dat

nursesv2: glpsol -m nursesv2.mod -d nurses.dat
